<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14776" started-at="2021-11-16T06:54:26Z" finished-at="2021-11-16T06:54:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14776" started-at="2021-11-16T06:54:26Z" finished-at="2021-11-16T06:54:41Z">
      <class name="com.Repairshop.tests.LoginTest">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="SetUp" is-config="true" duration-ms="1551" started-at="2021-11-16T12:24:26Z" finished-at="2021-11-16T12:24:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="PASS" signature="initialie()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="initialie" is-config="true" duration-ms="2" started-at="2021-11-16T12:24:28Z" finished-at="2021-11-16T12:24:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialie -->
        <test-method status="FAIL" signature="CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="CreateCustomer" duration-ms="8357" started-at="2021-11-16T12:24:28Z" finished-at="2021-11-16T12:24:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Repairshop.tests.LoginTest.CreateCustomer(LoginTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateCustomer -->
        <test-method status="PASS" signature="TearDown(org.testng.ITestResult)[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030]" name="TearDown" is-config="true" duration-ms="4700" started-at="2021-11-16T12:24:36Z" finished-at="2021-11-16T12:24:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateCustomer status=FAILURE method=LoginTest.CreateCustomer()[pri:0, instance:com.Repairshop.tests.LoginTest@18ce0030] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.Repairshop.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
